// Generated by gencpp from file snapstack_msgs/Wind.msg
// DO NOT EDIT!


#ifndef SNAPSTACK_MSGS_MESSAGE_WIND_H
#define SNAPSTACK_MSGS_MESSAGE_WIND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace snapstack_msgs
{
template <class ContainerAllocator>
struct Wind_
{
  typedef Wind_<ContainerAllocator> Type;

  Wind_()
    : header()
    , w_nominal()
    , w_gust()  {
    }
  Wind_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , w_nominal(_alloc)
    , w_gust(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _w_nominal_type;
  _w_nominal_type w_nominal;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _w_gust_type;
  _w_gust_type w_gust;





  typedef boost::shared_ptr< ::snapstack_msgs::Wind_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snapstack_msgs::Wind_<ContainerAllocator> const> ConstPtr;

}; // struct Wind_

typedef ::snapstack_msgs::Wind_<std::allocator<void> > Wind;

typedef boost::shared_ptr< ::snapstack_msgs::Wind > WindPtr;
typedef boost::shared_ptr< ::snapstack_msgs::Wind const> WindConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snapstack_msgs::Wind_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snapstack_msgs::Wind_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::snapstack_msgs::Wind_<ContainerAllocator1> & lhs, const ::snapstack_msgs::Wind_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.w_nominal == rhs.w_nominal &&
    lhs.w_gust == rhs.w_gust;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::snapstack_msgs::Wind_<ContainerAllocator1> & lhs, const ::snapstack_msgs::Wind_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace snapstack_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::snapstack_msgs::Wind_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snapstack_msgs::Wind_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snapstack_msgs::Wind_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snapstack_msgs::Wind_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snapstack_msgs::Wind_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snapstack_msgs::Wind_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snapstack_msgs::Wind_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43d6adbcc621b86e3d87893f8b41e553";
  }

  static const char* value(const ::snapstack_msgs::Wind_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43d6adbcc621b86eULL;
  static const uint64_t static_value2 = 0x3d87893f8b41e553ULL;
};

template<class ContainerAllocator>
struct DataType< ::snapstack_msgs::Wind_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snapstack_msgs/Wind";
  }

  static const char* value(const ::snapstack_msgs::Wind_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snapstack_msgs::Wind_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Vector3 w_nominal\n"
"geometry_msgs/Vector3 w_gust\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::snapstack_msgs::Wind_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snapstack_msgs::Wind_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.w_nominal);
      stream.next(m.w_gust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wind_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snapstack_msgs::Wind_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snapstack_msgs::Wind_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "w_nominal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.w_nominal);
    s << indent << "w_gust: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.w_gust);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAPSTACK_MSGS_MESSAGE_WIND_H
