# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from snapstack_msgs/VioFilterState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class VioFilterState(genpy.Message):
  _md5sum = "081bdc0c4d73ef878229dd1b85815934"
  _type = "snapstack_msgs/VioFilterState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# VioFilterState.msg
std_msgs/Header header

geometry_msgs/Pose pose
geometry_msgs/Twist twist  # includes gyro measurement for rates
geometry_msgs/Vector3 bw
geometry_msgs/Vector3 ba
geometry_msgs/Pose extrinsics  # camera-to-IMU transform

geometry_msgs/Vector3 accel_meas  # (IMU-frame) raw accel measurement

int32 N  # error state dimension
float32[] error_cov  # NxN error covariance.
                     # For consistency, leading 21 terms are ordered [pos, vel, Rwb, bw, ba, Rcb, tcb].

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','pose','twist','bw','ba','extrinsics','accel_meas','N','error_cov']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose','geometry_msgs/Twist','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Pose','geometry_msgs/Vector3','int32','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pose,twist,bw,ba,extrinsics,accel_meas,N,error_cov

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VioFilterState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      if self.bw is None:
        self.bw = geometry_msgs.msg.Vector3()
      if self.ba is None:
        self.ba = geometry_msgs.msg.Vector3()
      if self.extrinsics is None:
        self.extrinsics = geometry_msgs.msg.Pose()
      if self.accel_meas is None:
        self.accel_meas = geometry_msgs.msg.Vector3()
      if self.N is None:
        self.N = 0
      if self.error_cov is None:
        self.error_cov = []
    else:
      self.header = std_msgs.msg.Header()
      self.pose = geometry_msgs.msg.Pose()
      self.twist = geometry_msgs.msg.Twist()
      self.bw = geometry_msgs.msg.Vector3()
      self.ba = geometry_msgs.msg.Vector3()
      self.extrinsics = geometry_msgs.msg.Pose()
      self.accel_meas = geometry_msgs.msg.Vector3()
      self.N = 0
      self.error_cov = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_29di().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.bw.x, _x.bw.y, _x.bw.z, _x.ba.x, _x.ba.y, _x.ba.z, _x.extrinsics.position.x, _x.extrinsics.position.y, _x.extrinsics.position.z, _x.extrinsics.orientation.x, _x.extrinsics.orientation.y, _x.extrinsics.orientation.z, _x.extrinsics.orientation.w, _x.accel_meas.x, _x.accel_meas.y, _x.accel_meas.z, _x.N))
      length = len(self.error_cov)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.error_cov))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      if self.bw is None:
        self.bw = geometry_msgs.msg.Vector3()
      if self.ba is None:
        self.ba = geometry_msgs.msg.Vector3()
      if self.extrinsics is None:
        self.extrinsics = geometry_msgs.msg.Pose()
      if self.accel_meas is None:
        self.accel_meas = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 236
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.bw.x, _x.bw.y, _x.bw.z, _x.ba.x, _x.ba.y, _x.ba.z, _x.extrinsics.position.x, _x.extrinsics.position.y, _x.extrinsics.position.z, _x.extrinsics.orientation.x, _x.extrinsics.orientation.y, _x.extrinsics.orientation.z, _x.extrinsics.orientation.w, _x.accel_meas.x, _x.accel_meas.y, _x.accel_meas.z, _x.N,) = _get_struct_29di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.error_cov = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_29di().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.bw.x, _x.bw.y, _x.bw.z, _x.ba.x, _x.ba.y, _x.ba.z, _x.extrinsics.position.x, _x.extrinsics.position.y, _x.extrinsics.position.z, _x.extrinsics.orientation.x, _x.extrinsics.orientation.y, _x.extrinsics.orientation.z, _x.extrinsics.orientation.w, _x.accel_meas.x, _x.accel_meas.y, _x.accel_meas.z, _x.N))
      length = len(self.error_cov)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.error_cov.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      if self.bw is None:
        self.bw = geometry_msgs.msg.Vector3()
      if self.ba is None:
        self.ba = geometry_msgs.msg.Vector3()
      if self.extrinsics is None:
        self.extrinsics = geometry_msgs.msg.Pose()
      if self.accel_meas is None:
        self.accel_meas = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 236
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.bw.x, _x.bw.y, _x.bw.z, _x.ba.x, _x.ba.y, _x.ba.z, _x.extrinsics.position.x, _x.extrinsics.position.y, _x.extrinsics.position.z, _x.extrinsics.orientation.x, _x.extrinsics.orientation.y, _x.extrinsics.orientation.z, _x.extrinsics.orientation.w, _x.accel_meas.x, _x.accel_meas.y, _x.accel_meas.z, _x.N,) = _get_struct_29di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.error_cov = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_29di = None
def _get_struct_29di():
    global _struct_29di
    if _struct_29di is None:
        _struct_29di = struct.Struct("<29di")
    return _struct_29di
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
