// Generated by gencpp from file behavior_selector/MissionModeChangeResponse.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGERESPONSE_H
#define BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_selector
{
template <class ContainerAllocator>
struct MissionModeChangeResponse_
{
  typedef MissionModeChangeResponse_<ContainerAllocator> Type;

  MissionModeChangeResponse_()
    : RECEIVED(false)  {
    }
  MissionModeChangeResponse_(const ContainerAllocator& _alloc)
    : RECEIVED(false)  {
  (void)_alloc;
    }



   typedef uint8_t _RECEIVED_type;
  _RECEIVED_type RECEIVED;





  typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MissionModeChangeResponse_

typedef ::behavior_selector::MissionModeChangeResponse_<std::allocator<void> > MissionModeChangeResponse;

typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeResponse > MissionModeChangeResponsePtr;
typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeResponse const> MissionModeChangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator1> & lhs, const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.RECEIVED == rhs.RECEIVED;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator1> & lhs, const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_selector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deaed58dd82a93233dc3cd85c4d94e40";
  }

  static const char* value(const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdeaed58dd82a9323ULL;
  static const uint64_t static_value2 = 0x3dc3cd85c4d94e40ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_selector/MissionModeChangeResponse";
  }

  static const char* value(const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool RECEIVED\n"
;
  }

  static const char* value(const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RECEIVED);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionModeChangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_selector::MissionModeChangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "RECEIVED: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RECEIVED);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGERESPONSE_H
