// Generated by gencpp from file behavior_selector/MissionModeChange.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGE_H
#define BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGE_H

#include <ros/service_traits.h>


#include <behavior_selector/MissionModeChangeRequest.h>
#include <behavior_selector/MissionModeChangeResponse.h>


namespace behavior_selector
{

struct MissionModeChange
{

typedef MissionModeChangeRequest Request;
typedef MissionModeChangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionModeChange
} // namespace behavior_selector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::behavior_selector::MissionModeChange > {
  static const char* value()
  {
    return "485ed44d9d9a6cafffa6f772d726a264";
  }

  static const char* value(const ::behavior_selector::MissionModeChange&) { return value(); }
};

template<>
struct DataType< ::behavior_selector::MissionModeChange > {
  static const char* value()
  {
    return "behavior_selector/MissionModeChange";
  }

  static const char* value(const ::behavior_selector::MissionModeChange&) { return value(); }
};


// service_traits::MD5Sum< ::behavior_selector::MissionModeChangeRequest> should match
// service_traits::MD5Sum< ::behavior_selector::MissionModeChange >
template<>
struct MD5Sum< ::behavior_selector::MissionModeChangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::behavior_selector::MissionModeChange >::value();
  }
  static const char* value(const ::behavior_selector::MissionModeChangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::behavior_selector::MissionModeChangeRequest> should match
// service_traits::DataType< ::behavior_selector::MissionModeChange >
template<>
struct DataType< ::behavior_selector::MissionModeChangeRequest>
{
  static const char* value()
  {
    return DataType< ::behavior_selector::MissionModeChange >::value();
  }
  static const char* value(const ::behavior_selector::MissionModeChangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::behavior_selector::MissionModeChangeResponse> should match
// service_traits::MD5Sum< ::behavior_selector::MissionModeChange >
template<>
struct MD5Sum< ::behavior_selector::MissionModeChangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::behavior_selector::MissionModeChange >::value();
  }
  static const char* value(const ::behavior_selector::MissionModeChangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::behavior_selector::MissionModeChangeResponse> should match
// service_traits::DataType< ::behavior_selector::MissionModeChange >
template<>
struct DataType< ::behavior_selector::MissionModeChangeResponse>
{
  static const char* value()
  {
    return DataType< ::behavior_selector::MissionModeChange >::value();
  }
  static const char* value(const ::behavior_selector::MissionModeChangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGE_H
