// Generated by gencpp from file behavior_selector/MissionModeChangeRequest.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGEREQUEST_H
#define BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_selector
{
template <class ContainerAllocator>
struct MissionModeChangeRequest_
{
  typedef MissionModeChangeRequest_<ContainerAllocator> Type;

  MissionModeChangeRequest_()
    : mode(0)  {
    }
  MissionModeChangeRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(END)
  #undef END
#endif
#if defined(_WIN32) && defined(KILL)
  #undef KILL
#endif

  enum {
    START = 1u,
    END = 2u,
    KILL = 3u,
  };


  typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MissionModeChangeRequest_

typedef ::behavior_selector::MissionModeChangeRequest_<std::allocator<void> > MissionModeChangeRequest;

typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeRequest > MissionModeChangeRequestPtr;
typedef boost::shared_ptr< ::behavior_selector::MissionModeChangeRequest const> MissionModeChangeRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator1> & lhs, const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator1> & lhs, const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_selector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c83eaecb198976dfe0f3ab2713b48c0";
  }

  static const char* value(const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c83eaecb198976dULL;
  static const uint64_t static_value2 = 0xfe0f3ab2713b48c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_selector/MissionModeChangeRequest";
  }

  static const char* value(const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
"uint8 START  = 1\n"
"uint8 END    = 2\n"
"uint8 KILL   = 3\n"
;
  }

  static const char* value(const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionModeChangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_selector::MissionModeChangeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_SELECTOR_MESSAGE_MISSIONMODECHANGEREQUEST_H
